export function formatReport({ patientName, patientDate, studyType, technique, findings, impression }) {
  return `RADIOLOGY REPORT
================
Patient: ${patientName || ''}          Date: ${patientDate || ''}
Study: ${studyType || ''}

TECHNIQUE
---------
${technique || ''}

FINDINGS
--------
${findings || ''}

IMPRESSION
----------
${impression || ''}

Report generated by Radiology Report Generator`;
}

export function exportUserData(userTemplates, userPhrases) {
  const blob = new Blob(
    [JSON.stringify({ templates: userTemplates, phrases: userPhrases }, null, 2)],
    { type: 'application/json' },
  );
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'radiology-data.json';
  a.click();
  URL.revokeObjectURL(url);
}

export function importUserData(file, setUserTemplates, setUserPhrases) {
  const reader = new FileReader();
  reader.onload = () => {
    try {
      const data = JSON.parse(reader.result);
      if (data.templates) {
        setUserTemplates(prev => mergeDeep(prev, data.templates));
      }
      if (data.phrases) {
        setUserPhrases(prev => mergePhrases(prev, data.phrases));
      }
    } catch (err) {
      console.error('Failed to import radiology data:', err);
    }
  };
  reader.readAsText(file);
}

function mergeDeep(target, source) {
  const result = { ...target };
  for (const key of Object.keys(source)) {
    if (typeof source[key] === 'object' && source[key] !== null && !Array.isArray(source[key])) {
      result[key] = mergeDeep(result[key] || {}, source[key]);
    } else {
      result[key] = source[key];
    }
  }
  return result;
}

function mergePhrases(target, source) {
  const result = { ...target };
  for (const key of Object.keys(source)) {
    const existing = new Set(result[key] || []);
    for (const phrase of source[key]) existing.add(phrase);
    result[key] = Array.from(existing);
  }
  return result;
}
